import gym
import numpy as np
from gym.envs.registration import register

from wrappers import GridPosFeatureWrapper
from cirl_algs import RLSearchCirlAlg

register(
    id='FrozenLakeNotSlippery-v0',
    entry_point='gym.envs.toy_text:FrozenLakeEnv',
    kwargs={'map_name' : '4x4', 'is_slippery': False},
    max_episode_steps=100,
    reward_threshold=0.78, # optimum = .8196
)

# Generated by 10,000 expert runs on frozen lake (slippery)
expert_features = np.array(
    [0.29300975, 0.00480033, 0.00983885, 0.,
     0.24151374, 0.00251319, 0.01495273, 0.00242812,
     0.16385533, 0.08998858, 0.0352405,  0.,
     0.        , 0.0711251,  0.05288627, 0.01784751 ])

env = GridPosFeatureWrapper(gym.make('FrozenLakeNotSlippery-v0'))
cirl_test = RLSearchCirlAlg(env, expert_features)

print(cirl_test.cirl_trajectory())
